// languageCodeMapping.js

module.exports = {
  'es-US': 'Spanish (US)',
  'eu-ES': 'Basque (Spain)',
  'gl-ES': 'Galician (Spain)',
  'mr-IN': 'Marathi (India)',
  'pa-IN': 'Punjabi (India)',
  'sv-SE': 'Swedish (Sweden)',
  'ta-IN': 'Tamil (India)',
  'yue-HK': 'Cantonese (Hong Kong)',
  'bn-IN': 'Bengali (India)',
  'cmn-CN': 'Mandarin Chinese (China)',
  'cmn-TW': 'Mandarin Chinese (Taiwan)',
  'gu-IN': 'Gujarati (India)',
  'ja-JP': 'Japanese (Japan)',
  'kn-IN': 'Kannada (India)',
  'ml-IN': 'Malayalam (India)',
  'nl-BE': 'Dutch (Belgium)',
  'af-ZA': 'Afrikaans (South Africa)',
  'ar-XA': 'Arabic',
  'bg-BG': 'Bulgarian (Bulgaria)',
  'cs-CZ': 'Czech (Czech Republic)',
  'da-DK': 'Danish (Denmark)',
  'de-DE': 'German (Germany)',
  'en-AU': 'English (Australia)',
  'en-GB': 'English (United Kingdom)',
  'en-IN': 'English (India)',
  'en-US': 'English (United States)',
  'es-ES': 'Spanish (Spain)',
  'fi-FI': 'Finnish (Finland)',
  'fr-CA': 'French (Canada)',
  'fr-FR': 'French (France)',
  'he-IL': 'Hebrew (Israel)',
  'hi-IN': 'Hindi (India)',
  'hu-HU': 'Hungarian (Hungary)',
  'is-IS': 'Icelandic (Iceland)',
  'lt-LT': 'Lithuanian (Lithuania)',
  'lv-LV': 'Latvian (Latvia)',
  'ms-MY': 'Malay (Malaysia)',
  'nb-NO': 'Norwegian Bokmål (Norway)',
  'nl-NL': 'Dutch (Netherlands)',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'ro-RO': 'Romanian (Romania)',
  'ru-RU': 'Russian (Russia)',
  'sk-SK': 'Slovak (Slovakia)',
  'sr-RS': 'Serbian (Serbia)',
  'th-TH': 'Thai (Thailand)',
  'uk-UA': 'Ukrainian (Ukraine)',
  'te-IN': 'Telugu (India)',
  'el-GR': 'Greek (Greece)',
  'tr-TR': 'Turkish (Turkey)',
  'id-ID': 'Indonesian (Indonesia)',
  'fil-PH': 'Filipino (Philippines)',
  'it-IT': 'Italian (Italy)',
  'pl-PL': 'Polish (Poland)',
  'vi-VN': 'Vietnamese (Vietnam)',
  'ca-ES': 'Catalan (Spain)',
  'ko-KR': 'Korean (South Korea)',
};

/* const languageList = [
  { "code": "es-US", "name": "Spanish (US)" },
  { "code": "eu-ES", "name": "Spanish (Spain)" },
  { "code": "gl-ES", "name": "Galician (Spain)" },
  { "code": "mr-IN", "name": "Marathi (India)" },
  { "code": "pa-IN", "name": "Punjabi (India)" },
  { "code": "sv-SE", "name": "Swedish (Sweden)" },
  { "code": "ta-IN", "name": "Tamil (India)" },
  { "code": "yue-HK", "name": "Cantonese (Hong Kong)" },
  { "code": "bn-IN", "name": "Bengali (India)" },
  { "code": "cmn-CN", "name": "Mandarin Chinese (China)" },
  { "code": "cmn-TW", "name": "Mandarin Chinese (Taiwan)" },
  { "code": "gu-IN", "name": "Gujarati (India)" },
  { "code": "ja-JP", "name": "Japanese (Japan)" },
  { "code": "kn-IN", "name": "Kannada (India)" },
  { "code": "ml-IN", "name": "Malayalam (India)" },
  { "code": "nl-BE", "name": "Dutch (Belgium)" },
  { "code": "af-ZA", "name": "Afrikaans (South Africa)" },
  { "code": "ar-XA", "name": "Arabic (Arab World)" },
  { "code": "bg-BG", "name": "Bulgarian (Bulgaria)" },
  { "code": "cs-CZ", "name": "Czech (Czech Republic)" },
  { "code": "da-DK", "name": "Danish (Denmark)" },
  { "code": "de-DE", "name": "German (Germany)" },
  { "code": "en-AU", "name": "English (Australia)" },
  { "code": "en-GB", "name": "English (United Kingdom)" },
  { "code": "en-IN", "name": "English (India)" },
  { "code": "en-US", "name": "English (United States)" },
  { "code": "es-ES", "name": "Spanish (Spain)" },
  { "code": "fi-FI", "name": "Finnish (Finland)" },
  { "code": "fr-CA", "name": "French (Canada)" },
  { "code": "fr-FR", "name": "French (France)" },
  { "code": "he-IL", "name": "Hebrew (Israel)" },
  { "code": "hi-IN", "name": "Hindi (India)" },
  { "code": "hu-HU", "name": "Hungarian (Hungary)" },
  { "code": "is-IS", "name": "Icelandic (Iceland)" },
  { "code": "lt-LT", "name": "Lithuanian (Lithuania)" },
  { "code": "lv-LV", "name": "Latvian (Latvia)" },
  { "code": "ms-MY", "name": "Malay (Malaysia)" },
  { "code": "nb-NO", "name": "Norwegian Bokmål (Norway)" },
  { "code": "nl-NL", "name": "Dutch (Netherlands)" },
  { "code": "pt-BR", "name": "Portuguese (Brazil)" },
  { "code": "pt-PT", "name": "Portuguese (Portugal)" },
  { "code": "ro-RO", "name": "Romanian (Romania)" },
];
 */
